### PR TITLE
Restrict to one cronjob at a time

### PR DESCRIPTION
**Pull request by lcarva**
Signed-off-by: Luiz Carvalho <lucarval@redhat.com>

### CODE REVIEW

**Comment by accorvin** [comment]
Oh man, I had no idea this was a thing. You rock. I'm totally going to copy this and put it in all of the other cron jobs I have running in openshift.

**Comment by lcarva** [comment]
@accorvin :smile: Also pay attention to the `restartPolicy` which can be a bit misleading: https://docs.openshift.com/container-platform/3.9/dev_guide/jobs.html#creating-a-job-known-issues

**Comment by accorvin** [comment]
Yeah I've already played with that some, and agree that it's a tricky one. 👍 to this from me by the way, but I imagine you'll want someone from the team to review it.

**Comment by mprahl** [comment]
:+1:

**Pull request merged**
