### PR TITLE
Run less frequently.

### PR DESCRIPTION
**Pull request by ralphbean**
Github.com rate-limited us again today.  Maybe this will help?

### CODE REVIEW

**Comment by yashvardhannanavati** [comment]
:+1:

**Comment by accorvin** [comment]
Looks good to me. I think someone other than me should merge/deploy this (using the instructions in the readme). Anyone want to volunteer?

**Comment by yashvardhannanavati** [comment]
Sure, I can do it (deployment). Could you please review it after it's done just to make sure I have done it correctly?

Ralph will have to merge this though :)

**Comment by ralphbean** [comment]
@yashvardhannanavati, you should have rights to merge now.  :)

**Comment by yashvardhannanavati** [comment]
Thanks Ralph!

**Comment by yashvardhannanavati** [comment]
@accorvin I have updated the openshift template. Could you please confirm that it's done properly whenever you have time :)

**Comment by yashvardhannanavati** [comment]
Ah, I checked the logs and it looks fine

**Pull request merged**
